import { motion } from 'motion/react';
import { WEEK_BLURB } from '../lib/encouragements.js';
import { weeklyStreak } from '../lib/garden.js';

function dayNumber(dayKey) { return dayKey.match(/\d+/)?.[0]?.padStart(2, '0') || '01'; }

export default function Home({ appName, plan, weeks, week, onWeek, onStart, rewards, onClearRewards }) {
  const days = plan[week] ? Object.values(plan[week]) : [];
  const streak = weeklyStreak(rewards);
  const totalMinutes = Math.round(rewards.reduce((sum, reward) => sum + (reward.seconds || 0), 0) / 60);
  return <div className="screen home-screen">
    <section className="cover-intro"><p className="section-label">WORKOUT PLAN FOR MY</p><h1 className="cover-title">{appName}</h1><p className="cover-deck">Three days a week.</p></section>
    <section className="phase-section" aria-label="Training phase"><div className="section-heading"><div><p className="section-label">THE PROGRAM</p><span className="phase-helper">Choose a training block to begin</span></div><span className="section-count">{weeks.length} BLOCKS</span></div><div className="block-index">{weeks.map((item, index) => { const active = week === item; return <motion.button key={item} className={`block-option ${active ? 'active' : ''}`} onClick={() => onWeek(item)} aria-selected={active} whileTap={{ scale: .99 }}><span className="block-number">{String(index + 1).padStart(2, '0')}</span><span className="block-content"><strong>{item.replace('Week ', 'WEEKS ')}</strong>{active && <small>{WEEK_BLURB[item] || 'Choose a session to begin.'}</small>}</span><span className="block-mark" aria-hidden="true">{active ? '↗' : '—'}</span></motion.button>; })}</div></section>
    <section className="sessions-section"><div className="section-heading"><p className="section-label">SELECT A SESSION</p><span className="section-count">{days.length} DAYS / WEEK</span></div><div className="session-list">{days.map((day, index) => { const mains = day.exercises.filter(exercise => exercise.type.toLowerCase() === 'main').length; return <motion.button key={day.key} className="session-row" whileTap={{ scale: .985 }} onClick={() => onStart(day.key)}><span className="session-number">{dayNumber(day.key)}</span><span className="session-copy"><span className="session-kicker">DAY {dayNumber(day.key)} / {index === 0 ? 'FOUNDATION' : index === 1 ? 'STRENGTH' : 'FINISH'}</span><strong>{day.title}</strong><small>{String(day.exercises.length).padStart(2, '0')} MOVEMENTS <i>·</i> {mains} MAIN LIFTS <i>·</i> ~{Math.round(day.exercises.length * 4.5)} MIN</small></span><span className="session-arrow" aria-hidden="true">↗</span></motion.button>; })}</div></section>
    <section className="progress-section"><div className="section-heading"><p className="section-label">YOUR PRACTICE</p>{rewards.length > 0 && <button className="text-action" onClick={onClearRewards}>RESET HISTORY</button>}</div>{rewards.length === 0 ? <p className="empty-note">Your completed sessions will live here.<br />Start with one good rep.</p> : <><div className="practice-stats"><div><strong>{String(rewards.length).padStart(2, '0')}</strong><span>SESSIONS</span></div><div><strong>{String(streak).padStart(2, '0')}</strong><span>WEEK STREAK</span></div><div><strong>{String(totalMinutes).padStart(2, '0')}</strong><span>MINUTES</span></div></div><div className="practice-history">{rewards.slice().reverse().slice(0, 4).map(reward => <div className="history-row" key={reward.id}><span className="reward-icecream" aria-hidden="true">🍦</span><span>{reward.reward || 'filter coffee softy'}</span><small>{new Date(reward.at).toLocaleDateString()}</small></div>)}</div></>}</section>
    <footer className="page-footer"><span>MOVE THAT BOOTY</span></footer>
  </div>;
}
